### ISSUE TITLE
display of documentation in browser

### ISSUE THREAD

**Issue by AmosEgel** [scottprahl/miepython#2]
Hi Scott, thanks for this very helpful tool!

When looking at the [introductory documentation page](https://github.com/scottprahl/miepython/blob/master/doc/01_basics.ipynb) in a browser (Chrome, Internet Explorer), the formulas are displayed in a strange way (see the following snippet).

![image](https://user-images.githubusercontent.com/16704045/39363089-4fbeb548-4a29-11e8-8f87-6ae8cfef183f.png)

I think this is a bit confusing, as one could read the second line as x = 2 pi r / lambda / n, while it is actually x = 2 pi r / (lambda / n), right?

**Comment by scottprahl** [comment]
Somehow, I missed your bug report when it was submitted.  Sorry.

You are correct, the markup is rendered incorrectly.  The problem is that Github does not render $x \over y$ properly, but does so for $\frac{x}{y}$.  I have recently updated all the jupyter notebooks so that things now render properly.

Thanks for the report.
