### ISSUE TITLE
coefficents calculation at large size parameter gives unexpected results

### ISSUE THREAD

**Issue by ysBach** [scottprahl/miepython#4]
The following code gives results which I didn't expect:
```python
import numpy as np
import matplotlib.pyplot as plt

# if miepython is missing, do `pip install miepython`
import miepython as mp

m = 1.5 - 0.01j
x = np.logspace(-1, 5, 20)  # also in microns

qext, qsca, qback, g = mp.mie(m,x)
plt.plot(x, qext, 'b+-', label="Q_ext")
plt.plot(x, qsca, 'r+:', label="Q_sca")
plt.plot(x, qback, 'g+:', label="Q_back")
plt.plot(x, g, 'r+-', label="<cos>")
plt.plot(x, qext - g * qsca, 'kx-', label="Q_pr")
plt.xscale('log')
plt.yscale('log')
plt.xlabel("size parameter")
plt.legend()
plt.grid()
```

The resulting figure:
![image](https://user-images.githubusercontent.com/17214293/52427479-53c91100-2b43-11e9-8c61-766d01747306.png)

At size parameter larger than ~ 5000, all coefficients except for ``qext`` (expected to be ~ 2) deviate largely, and ``qpr`` becomes negative.

As I am not so familiar with scattering theory, I couldn't understand/interpret this result. Is this an expected behavior?

**Comment by scottprahl** [comment]
You definitely found a bug!  Nice work.

My excuse is that I have not cared about very large spheres and therefore just did not test these cases.  I will upload a new jupyter notebook to the doc section showing 

It turns out that the flag to determine if upwards or downward recurrence relations should be used was messed up.  I have a fix for this that solves the Qsca, Qext, and Qpr problems.  I am still a bit unsure if the fixes the problem with Qback, but I don't have the time to investigate it at the moment.

I uploaded the fix to miepython.py to github.  Once I convince myself that Qback is also fine for large spheres, then I will release a new version.

![newtest](https://user-images.githubusercontent.com/1901078/52457917-1d729e00-2b11-11e9-8838-970254cc2f3f.png)

**Comment by ysBach** [comment]
@scottprahl Thank you so much for your prompt reply and update of the package! :)

I have tested 273f46ff53ef4f00ca68d0723c87fa33100a2a8f and it works perfectly, at least seemingly.

FYI)
The reason I used your ``miepython`` to my research is I wanted to calculate the black-body spectrum averaged $ Q_\mathrm{pr} $, $ \bar{Q} $, of certain mineral, and now the results are as I expected:
(The codes are very long and time consuming so I didn't attach any here)
![image](https://user-images.githubusercontent.com/17214293/52518799-0d36fc00-2c94-11e9-872c-d9f73b3a0c6a.png)
Using the previous code, the $\bar{Q}_\mathrm{pr}$ value gets negative when $a > 100 \mathrm{\mu m}$, and the trend does not seem to converge to 1 even when particle size is very large. 

But this new code shows that $\bar{Q}_\mathrm{pr}$ is **always positive** and **converges to unity** when the particle is very large (compared to the wavelengths of interest).

**Comment by scottprahl** [comment]
Lovely graphs!

I want to thank you again for your bug report.  It was just the right thing that I needed to see to track down the bug.  I knew something was awry with large sphere calculations but attributed the problems to round-off when summing many terms.  Your first graph showed me that the transition was sudden and therefore I was able to change one line of code that fixed calculations for all large sphere.
